[profile.default]
src = 'src'
out = 'out'
tests = 'test'
libs = ["node_modules"]
verbosity = 4
evm_version = 'cancun'

gas_reports = [
    "Strategy",
    "OnlyBoost",
    "CRVStrategy",
    "ConvexImplementation",
    "ConvexMinimalProxyFactory"
  ]

# Enable before deploying.
optimizer = true
optimizers_runs = 200

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"