[profile.default]
src = 'src'
out = 'out'
tests = 'test'
libs = ['lib']
verbosity = 3
evm_version = "shanghai"

ffi = true
optimizers_runs = 200

remappings = [
    "solady/=lib/solady/src/"
]

# Failed
# _155_Deposit_Test
# _151_Deposit_Test
