[profile.default]
src = 'src'
out = 'out'
tests = 'test'
libs = ['lib']
verbosity = 3
evm_version = 'shanghai'

  gas_reports = [
    "Strategy",
    "OnlyBoost",
    "CRVStrategy",
    "ConvexImplementation",
    "ConvexMinimalProxyFactory"
  ]

ffi = true

# Enable before deploying.
optimizer = true
optimizers_runs = 200

remappings = [
    "solady/=lib/solady/src/"
]