[profile.default]
src = 'src'
out = 'out'
tests = 'test'
libs = ["node_modules"]
verbosity = 3
evm_version = 'cancun'

gas_reports = [
    "Strategy",
    "OnlyBoost",
    "CRVStrategy",
    "ConvexImplementation",
    "ConvexMinimalProxyFactory"
  ]

# Enable before deploying.
optimizer = true
optimizers_runs = 200
