[profile.default]
src = 'src'
out = 'out'
tests = 'test'
libs = ['lib']
verbosity = 3
evm_version = "shanghai"
  gas_reports = [
    "CRV_OB_Strategy",
    "ConvexImplementation",
    "ConvexMinimalProxyFactory"
  ]

ffi = true

# Enable before deploying.
optimizer = false
optimizers_runs = 200

remappings = [
    "solady/=lib/solady/src/"
]