[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 3
evm_version = "shanghai"

fs_permissions = [{ access = "read", path = "./test/python/pools.json"}]

[invariant]
runs = 100
depth = 10
fail_on_revert = false

remappings = [
    "solady/=lib/solady/src/"
]